version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis://redis:6379
      - SERVER_ADDR=0.0.0.0:8080
    depends_on:
      - redis

  redis:
    image: "redis:7-alpine"